name: THINQ I/O
favicon: null
layout_spectrum: 0.9147054783534259
typography_spectrum: 0.4146761631127447
title: Learning is not a luxury. It is a human right.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#004cba'
    - '#007cd9'
    - '#9af4ff'
    - '#70c9ea'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.9794939095154405
  rhythmicContrast: 0.32258989149704576
purpose: []
